import { InventoryItem } from '@/components/dashboard/InventoryTable';

export const mockInventory: InventoryItem[] = [
  {
    id: '1',
    name: 'Paracetamol 500mg',
    category: 'Tablets',
    batchNumber: 'PCM-2024-001',
    quantity: 2500,
    reorderLevel: 500,
    expiryDate: '2025-12-15',
    supplier: 'Cipla Ltd',
    status: 'healthy',
  },
  {
    id: '2',
    name: 'Amoxicillin 250mg',
    category: 'Capsules',
    batchNumber: 'AMX-2024-045',
    quantity: 180,
    reorderLevel: 200,
    expiryDate: '2025-06-20',
    supplier: 'Sun Pharma',
    status: 'low',
  },
  {
    id: '3',
    name: 'Insulin Glargine 100U/ml',
    category: 'Injections',
    batchNumber: 'INS-2024-012',
    quantity: 45,
    reorderLevel: 100,
    expiryDate: '2025-03-01',
    supplier: 'Novo Nordisk',
    status: 'critical',
  },
  {
    id: '4',
    name: 'Cough Syrup 100ml',
    category: 'Syrups',
    batchNumber: 'CGH-2024-089',
    quantity: 350,
    reorderLevel: 150,
    expiryDate: '2025-09-30',
    supplier: 'Dabur',
    status: 'healthy',
  },
  {
    id: '5',
    name: 'Diclofenac Gel 30g',
    category: 'Ointments',
    batchNumber: 'DCL-2024-023',
    quantity: 120,
    reorderLevel: 100,
    expiryDate: '2024-02-15',
    supplier: 'Ranbaxy',
    status: 'expired',
  },
  {
    id: '6',
    name: 'Omeprazole 20mg',
    category: 'Capsules',
    batchNumber: 'OMP-2024-067',
    quantity: 890,
    reorderLevel: 300,
    expiryDate: '2025-11-10',
    supplier: 'Dr. Reddys',
    status: 'healthy',
  },
  {
    id: '7',
    name: 'Metformin 500mg',
    category: 'Tablets',
    batchNumber: 'MET-2024-034',
    quantity: 1200,
    reorderLevel: 400,
    expiryDate: '2026-01-20',
    supplier: 'Torrent Pharma',
    status: 'healthy',
  },
  {
    id: '8',
    name: 'Ciprofloxacin Eye Drops',
    category: 'Drops',
    batchNumber: 'CIP-2024-091',
    quantity: 65,
    reorderLevel: 80,
    expiryDate: '2025-04-15',
    supplier: 'Alcon',
    status: 'low',
  },
];

export const mockAlerts = [
  {
    id: '1',
    type: 'stockout' as const,
    message: 'Stock depleted, immediate reorder required',
    medicineName: 'Insulin Glargine 100U/ml',
    severity: 'high' as const,
    time: '2 hours ago',
  },
  {
    id: '2',
    type: 'expiry_warning' as const,
    message: 'Expires in 30 days - consider clearance sale',
    medicineName: 'Diclofenac Gel 30g',
    severity: 'high' as const,
    time: '5 hours ago',
  },
  {
    id: '3',
    type: 'low_stock' as const,
    message: 'Below reorder level (180/200)',
    medicineName: 'Amoxicillin 250mg',
    severity: 'medium' as const,
    time: '1 day ago',
  },
  {
    id: '4',
    type: 'low_stock' as const,
    message: 'Below reorder level (65/80)',
    medicineName: 'Ciprofloxacin Eye Drops',
    severity: 'medium' as const,
    time: '1 day ago',
  },
];

export const mockConsumptionData = [
  { name: 'Week 1', actual: 420, forecast: 450 },
  { name: 'Week 2', actual: 380, forecast: 420 },
  { name: 'Week 3', actual: 510, forecast: 480 },
  { name: 'Week 4', actual: 470, forecast: 500 },
  { name: 'Week 5', actual: 520, forecast: 510 },
  { name: 'Week 6', actual: 490, forecast: 530 },
  { name: 'Week 7', actual: null, forecast: 550 },
  { name: 'Week 8', actual: null, forecast: 570 },
  { name: 'Week 9', actual: null, forecast: 540 },
  { name: 'Week 10', actual: null, forecast: 560 },
];

export const mockForecastData = [
  {
    id: '1',
    medicineName: 'Paracetamol 500mg',
    currentStock: 2500,
    weeklyConsumption: 450,
    forecastedDemand: 1800,
    recommendedOrder: 0,
    daysUntilStockout: 38,
    confidence: 92,
  },
  {
    id: '2',
    medicineName: 'Amoxicillin 250mg',
    currentStock: 180,
    weeklyConsumption: 85,
    forecastedDemand: 340,
    recommendedOrder: 360,
    daysUntilStockout: 14,
    confidence: 87,
  },
  {
    id: '3',
    medicineName: 'Insulin Glargine 100U/ml',
    currentStock: 45,
    weeklyConsumption: 25,
    forecastedDemand: 100,
    recommendedOrder: 155,
    daysUntilStockout: 12,
    confidence: 94,
  },
  {
    id: '4',
    medicineName: 'Omeprazole 20mg',
    currentStock: 890,
    weeklyConsumption: 120,
    forecastedDemand: 480,
    recommendedOrder: 0,
    daysUntilStockout: 51,
    confidence: 89,
  },
  {
    id: '5',
    medicineName: 'Metformin 500mg',
    currentStock: 1200,
    weeklyConsumption: 200,
    forecastedDemand: 800,
    recommendedOrder: 0,
    daysUntilStockout: 42,
    confidence: 91,
  },
];

export const dashboardStats = {
  totalMedicines: 245,
  lowStockItems: 12,
  expiringItems: 8,
  totalValue: 4850000,
  monthlyConsumption: 15420,
  stockTurnover: 4.2,
};
